Master server communication
majormartintibor/PAS.Client pull request #3
Opened 2021-06-21 14:46 UTC by majormartintibor

2021-06-21 17:22 UTC, davidmunkacsi93 requested changes

2021-06-21 17:22 UTC, davidmunkacsi93 commented on PAS.Client.Services/PAS.Client.Services.csproj
> +    <ProjectReference Include="..\PAS.Client.Models\PAS.Client.Models.csproj" />
Why are you referencing the Models project?

2021-06-21 17:22 UTC, davidmunkacsi93 commented on PAS.Client/App.xaml.cs
> +            services.AddScoped<IClient, PAS.Client.Services.PASServerClient.Client>
The naming is still not perfect. Why don’t you name the generated client PASServerClient? Then it will implement an interface IPASServerClient.

2021-06-21 17:22 UTC, davidmunkacsi93 commented on PAS.Client/App.xaml.cs
> +                    new System.Net.Http.HttpClient())
Using System.Net.HTTP?

2021-06-21 17:22 UTC, davidmunkacsi93 commented on PAS.Client/ViewModels/LoginViewModel.cs
> +        public async void TestGet(object parameter)
The return type should Task.

2021-06-22 06:15 UTC, majormartintibor commented on PAS.Client.Services/PAS.Client.Services.csproj
> +    <ProjectReference Include="..\PAS.Client.Models\PAS.Client.Models.csproj" />
This was an accident. I had a TestGet class in the models and used that instead of the TestGet class generated. The TestGet under models project has since been removed just forgot to remove the reference.

2021-06-22 08:19 UTC, davidmunkacsi93 approved these changes

2021-06-22 08:19 UTC, davidmunkacsi93 commented on PAS.Client.Services/PAS.Client.Services.csproj
> +    <ProjectReference Include="..\PAS.Client.Models\PAS.Client.Models.csproj" />
The reference is still there ain't it?

2021-06-22 08:20 UTC, merged